Add LED status API
andig/fritzapi pull request #7
Opened 2018-03-05 14:41 UTC by chrmoritz

This PR adds support for getting and setting the LED status of a Fritz!Box. It also includes [a documentation for this new feature](https://github.com/chrmoritz/fritzapi/tree/led#led-status-functions).

This PR is a preparation for the corresponding `homebridge-fritz` PR, which will add these status LEDs as a lightbulb to homebridge: 

#### A little background on this feature.

A while ago AVM added support for deactivating the status LEDs from withing the LED settings page as a feature in Fritz!OS, but later decided to hide this feature again from all Fritz!Boxes (but not from the repeaters I think) for unknown reasons. But they didn't actual remove this feature as the POST endpoint is still working. It's just not accessible from the official web settings ui anymore.

Tested with a Fritz!Box 6490 and FRITZ!OS 6.87.
Nonetheless I think this is a very useful feature and everyone who has to sleep in the same room as their Fritz!Box will likely agree with me on this.

2018-04-16 10:29 UTC, andig requested changes

2018-04-16 10:29 UTC, andig commented on README.md
> +`getLEDStatus` returns an object containing the String typed `led_display` property with following possible values, which can also  be passed as the `status` parameter to `setLEDStatus`:
... with `led_display` containing the led status ...

I'd suggest cleaning up the API into receiving/returning a simple numeric value and performing object creation internally in the library.

2018-04-16 10:29 UTC, andig commented on index.js
> +function parseLEDStatusHTML(html)
same here- why not simply return 0..2 to make the API symmetric?

2018-04-23 18:28 UTC, andig commented
ping @chrmoritz do you still want to pursue this? Apart from the comments sofar I'd also suggest using:

  - 0: off
  - 1: on
  - 2 (or whatever value): automatic

what do you think?

2018-04-25 11:04 UTC, chrmoritz commented
Sure, I'm just a little short on time right now.

The values I've used are the one used by AVM. While I agree that this is bad API design, I'm not sure if it is worth the effort to translate on every API call between our values the one used by AVM. Maybe we could use some sort of enum to hide the ugliness, like exporting `LED_STATUS = {ON: 0, AUTO: 1, OFF: 2}`, so that you could use something like this:

```js
var fritz = require('./index.js');
fritz.setLEDStatus(sid, fritz.LED_STATUS.ON);
```

What do you think?

2018-04-25 12:14 UTC, andig commented
Sounds good though a simple (but intuitive :) number should do as well

2020-01-31 13:29 UTC, lavolp3 commented
I tried to use this code but the html request returns an empty html element for me. Can you confirm it still works?
Fritz OS v 7.12
FRITZ Box 7490

2020-02-02 16:51 UTC, chrmoritz commented
I don't think this code works in FritzOS v7+ anymore. But at least AVM did bring back the ability to choose between the `always on` and `on demand` in their officially web GUI.

One could try to bind to that, but this isn't that important (at least for me) anymore, since it's available in the GUI again. So I'm closing this PR.

2020-02-02 16:51 UTC, closed without merging